apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: repositories.gg.dev
spec:
  scope: Cluster
  group: gg.dev
  names:
    kind: Repository
    plural: repositories
    singular: repository
    shortNames:
      - repo
      - repos
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dryRun:
                  type: boolean
                externalName:
                  type: string
                permissions:
                  type: object
                  properties:
                    teams:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    users:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
