repos:
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)  
    args: ["--profile", "black"]

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    language_version: python3.10

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: ["--max-line-length=125", "--ignore=E203,W503"]

