apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: repositorypermission.kopf.dev
spec:
  scope: Cluster
  group: kopf.dev
  names:
    kind: RepositoryPermission
    plural: repositorypermissions
    singular: repositorypermission
    shortNames:
      - rp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
